server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

imgbb:
  api:
    key: d9680de93bbf1df4d5137d14cb20250e

spring:
  main:
    allow-circular-references: true

    mail:
      host: smtp.gmail.com
      port: 465
      username: "[본인이 사용할 이메일]"
      password: "[생성된 비밀번호]"
      properties:
        mail:
          smtp:
            auth: true
            timeout: 5000
            starttls:
              enable: true


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_test?serverTimezone=Asia/Seoul
    username: test
    password: mysql1234!

  mvc:
    view:
      prefix: /templates/
      suffix: .jsp

  jpa:
    open-in-view: false #run as시 쓰는 warn오류 위한
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    user:
      name: user
      password: 1111
    oauth2:
      client:
        registration:
          google:
            client-id: 312301276984-4tat5dqpetmd1m2t5ur65njbsfjtoqgu.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 2382923761892831
            client-secret: 19a0cf40742adc98894ce3e7f0c0b459
            scope:
              - email
              - public_profile

          naver:
            client-id: 8VcOP_62v7Hsyn5Vj2bd
            client-secret: J8s_dzqlk8
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver #구글,페북,트위터 등은 provider등록이 되어있어서 이걸 안적었던 것임

        provider:
          naver:
            authorization-uri:  https://nid.naver.com/oauth2.0/authorize #<a href="/oauth2/authorization/naver">에서 호출되는 주소
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키 값으로 네이버가 리턴해줌